# Generated by Django 4.2 on 2024-04-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num_joined',
            field=models.IntegerField(default=0),
        ),
    ]
