# Generated by Django 4.2 on 2024-04-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_remove_post_latitude_remove_post_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
